config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "projects#index"
  
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, presence: true
    validates :idea, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to @project
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def project_params
      params.require(:project).permit(:name, :idea, :tools)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with model: project do |form| %>
    <div>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
        <% project.errors.full_messages_for(:name).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :idea %><br>
        <%= form.text_area :idea %>
        <% project.errors.full_messages_for(:idea).each do |message| %>
        <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :tools %><br>
        <%= form.text_field :tools %>
        <% project.errors.full_messages_for(:tools).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "form", project: @project %>

app/views/projects/index.html.erb
<h1>Projects</h1>
<ul>
    <% @projects.each do |project| %>
        <li>
            <%= link_to project.name, project %>
            <%= project.idea %> <br>
            <b><em> Using: <%= project.tools %> </em></b><br>
        </li>
    <% end %>
</ul>
<div>
    <a href="/projects/new">Create new</a>
</div>

app/views/projects/new.html.erb
<h1> Prepare to Create Something Brilliant </h1>

<%= render "form", project: @project %>

app/views/projects/show.html.erb
<h1> <%= @project.name %> </h1>

<p> <%= @project.idea %> </p>

<ul>
    <li><%= link_to "Edit", edit_project_path(@project) %></li>
</ul>

<%= link_to "Back", root_path %>